### ISSUE TITLE
Error running elm-brunch 

### ISSUE THREAD

**Issue by michaelwa** [madsflensted/elm-brunch#12]
I'm getting the following error starting Brunch watch --server

`error: Compiling of src\justCompile.elm failed. Invalid regular expression: /^src[\]?/: Unterminated character class`

The regex seems to be tied settings from brunch-config.json file specifically the "elmFolder" property.
When the elmFolder is set to elmFolder: "src", then the error appears as above. However when it is omitted then the error switches to.

`error: Compiling of src\justCompile.elm failed. Invalid regular expression: /^null[\]?/: Unterminated character class`

**Comment by madsflensted** [comment]
Yes - looks like cross platform bug. Can I get you to clone elm-brunch and the run `npm test` in the checkout folder? And then paste the result here.

**Comment by madsflensted** [comment]
I have pushed a possible fix to github (not npm) - can I get you try using the source version?

**Comment by michaelwa** [comment]
Thanks for the quick reply!! 

Below is the test session results.

`C:\Users\Michael\Documents\src\elm-brunch [master ≡]> npm test

> elm-brunch@0.4.2 test C:\Users\Michael\Documents\src\elm-brunch
> mocha

'mocha' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
C:\Users\Michael\Documents\src\elm-brunch [master ≡]>`

I'm pretty much a noob here with node.js and I'm not sure what the steps are to installing from source versus npm. Also do I need to uninstall the current version first?

**Comment by madsflensted** [comment]
Ok,  try it in your project instead:

Take index.js from elm-brunch git repo and replace the one in your
node_modules\elm-brunch\ folder
Then just run brunch again

**Comment by michaelwa** [comment]
Thank you sir that seems to have done the trick!!

**Comment by madsflensted** [comment]
I have published a new version of the plugin that includes this fix
