### ISSUE TITLE
Multiple elm-package.json files

### ISSUE THREAD

**Issue by thatguyhampton** [madsflensted/elm-brunch#19]
## Problem

I have a project with a structure similar to the following:

```
    elm    
        details    
            Details.elm
            elm-package.json
        list
            ObjectList.elm
            elm-package.json
```

Each module has a different list of dependencies. How would you recommend using elm-brunch to build a project that can have multiple elm-package.json files? 
## Information
- [ ] elm-brunch version
- [ ] brunch version
- [ ] nodejs version
- [x] content of brunch-config.js
- [x] content of elm-package.json
- [ ] file layout for your elm files relative to root of project.
- [ ] Operating System

**Comment by thatguyhampton** [comment]
I took a look at elms way of compiling things and the library only gets compiled into my generated javascript file when it is imported. So for this reason I should be able to have just a single elm-package.json file with all of the shared dependencies because the unused ones will not affect the file size of the resulting compiled javascript files. So basically Hodor... and no fix needed. :)

**Comment by madsflensted** [comment]
Glad you worked it out
