### ISSUE TITLE
README needs more info to get started for a brunch n00b

### ISSUE THREAD

**Issue by ivanoats** [madsflensted/elm-brunch#2]
Could you post a complete brunch config instead of a snippet please? 

I'm not sure which directory elm files should go in, and what the rest of the brunch file should look like if my app is completely in Elm.

Thanks!

**Comment by madsflensted** [comment]
Hi,

You can find an example brunch config file here:
https://github.com/madsflensted/dots?files=1

Or you could look at this example by @urfolomeus
https://github.com/urfolomeus/seat_saver?files=1

Let me know if that answers your question

**Comment by ivanoats** [comment]
Hi, thanks for the examples. It's still not really enough info to get started easily. 

I have a simple brunch config [in this repo](https://github.com/ivanoats/Bingo), but it's not compiling the Elm files. Could you take a look please?

I'm willing to help contribute to the README once I understand how this plugin works better.

**Comment by ivanoats** [comment]
Nevermind, I needed to add my src/ directory to a paths.watched in the brunch config, then it found the elm files. 

I think that maybe the readme could contain a very simple brunch app skeleton example, would you like me to take a stab at it?

**Comment by madsflensted** [comment]
Glad you found the problem.
Contributions are welcome!
