### ISSUE TITLE
Request: 'merge' build strategy

### ISSUE THREAD

**Issue by lessless** [madsflensted/elm-brunch#21]
Right now each module is compiled as separate file. In addition to that, it will be good to have the option to output all compiled modules as a single file.

**Comment by madsflensted** [comment]
@lessless, yes it already has an issue #9 , and I was thinking that this should be the default behavior and separate output files should be something requiring configuration. What do you think?

**Comment by lessless** [comment]
@madscoaducom totally love it! :sparkling_heart:

**Comment by anronin** [comment]
@madsflensted i`m :+1: on set default behavior to merge files, like you said in https://github.com/madsflensted/elm-brunch/issues/9 each module's output file contain the entire elm core and thats not really good, i think so

**Comment by madsflensted** [comment]
For now it is possible to enable single file target via feature from #22
