### ISSUE TITLE
Confused about configuration

### ISSUE THREAD

**Issue by simonh1000** [madsflensted/elm-brunch#29]
## Problem

Elm is compiling the file I just saved, rather than Main.elm where my main function resides. As a result I don't get the new functionality when I save (and have to switch the Main.elm and fake a save of that) and I'm getting files such as app.js.map in /priv/static/js

I've looked at the examples,  but made no progress. Can you help?
## Information
- ["^0.7.0", ] elm-brunch version
- ["2.7.4" ] brunch version
- [6.7 ] nodejs version
- [see below  ] content of brunch-config.js
- [ see below] content of elm-package.json
- [web/elm ] file layout for your elm files relative to root of project.
- [ Ubuntu 16.04] Operating System
  
  elmBrunch: {
    // Set to path where `elm-make` is located, relative to `elmFolder` (optional)
    // executablePath: '../../node_modules/elm/binwrappers',
  
    // Set to path where elm-package.json is located, defaults to project root (optional)
    // if your elm files are not in /app then make sure to configure paths.watched in main brunch config
    // elmFolder: '.',
  
    // Set to the elm file(s) containing your "main" function
    // `elm make` handles all elm dependencies (required)
    // relative to `elmFolder`
    mainModules: ['web/elm/Main.elm'],
  
    // Defaults to 'js/' folder in paths.public (optional)
    // outputFolder: 'some/path/',
  
    // If specified, all mainModules will be compiled to a single file (optional and merged with outputFolder)
    outputFile: 'main.js',
  
    // optional: add some parameters that are passed to elm-make
    makeParameters : ['--warn']
  },

{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "web/elm", "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}

**Comment by madsflensted** [comment]
have you tried setting the `elmFolder` setting, and changing your
`mainModules` path accordingly?

**Comment by simonh1000** [comment]
I tried:

```
elmBrunch: {
    elmFolder: 'web/elm',
    mainModules: ['Main.elm'],
    outputFile: 'main.js',
    makeParameters : ['--warn']
},
```

and now I get the following when I run `mix phoenix.server`

```
Elm compile: web/elm/App.elm, to priv/static/js/app.js
Elm compile: web/elm/Decoders.elm, to priv/static/js/decoders.js
Elm compile: web/elm/Main.elm, to priv/static/js/main.js
```

and that results in multiple .js files

**Comment by madsflensted** [comment]
Ok.

Hadn't spotted that your elm-package.json was i your project root. Then
your original settings are the right ones.

What output do you get from the plugin when running in the 1st scenario?

**Comment by simonh1000** [comment]
I cut some files from the list before for simplicity. I deleted /priv/static/js and restarted phoenix. This is what I saw

```
Elm compile: web/elm/App.elm, to priv/static/js/app.js
Elm compile: web/elm/Decoders.elm, to priv/static/js/decoders.js
Elm compile: web/elm/DragDrop.elm, to priv/static/js/dragdrop.js
Elm compile: web/elm/DropZone.elm, to priv/static/js/dropzone.js
Elm compile: web/elm/FileReader.elm, to priv/static/js/filereader.js
Elm compile: web/elm/Main.elm, to priv/static/js/main.js
Elm compile: web/elm/MimeType.elm, to priv/static/js/mimetype.js
19 Oct 11:55:32 - info: compiled 14 files into 2 files, copied 3 in 1.9 sec
```

Could it have something to do with me using App.elm as a filename, while there is an app.js as part of the basic Phoenix setup

**Comment by madsflensted** [comment]
Looks like elm-brunch is not picking up the mainModules  configuration
item. Since it insists on compiling elm files to individual js targets

**Comment by simonh1000** [comment]
Is that something I can fix myself?

**Comment by madsflensted** [comment]
Not sure why.
You can try to add some debug to elm-brunch/index.js in your node_modules
folder and see if you can find out why.

The general idea is that any file being watched will cause all main modules
to be compiled instead of the file itself.

**Comment by madsflensted** [comment]
Closed due to inactivtiy
