### ISSUE TITLE
Unexpected end of input 

### ISSUE THREAD

**Issue by Dkendal** [madsflensted/elm-brunch#4]
Using version 0.3.1, brunch can't compile any elm files:

> iex(1)> Elm compile: Main.elm, in web/elm, to ../static/vendor/main.js
> 27 Sep 17:34:26 - error: Compiling of 'web/static/vendor/main.js' failed. Line 777: Unexpected end of input

After downgrading to 0.3.0, the problem goes away. This is with elm 2.0.0, Linux 3.16.0-37.

main.elm:

``` elm
module Main where

import Html exposing(..)

main = text "sup"
```

Elm has no issue compiling it with elm-make.

**Comment by madsflensted** [comment]
@Dkendal Could not reproduce this error, and it is a bit strange since 0.3.1 is purely a documentation update.

One thing that comes to mind reading the error message is that it looks like brunch is trying to read main.js before elm has finished writing it.

Can you post your brunch-config.js?

**Comment by Dkendal** [comment]
Upon revisiting this last night, I think vim was the real culprit. Vim saves files twice, once in a weird state, which would not be valid for compilation.

**Comment by Dkendal** [comment]
i.e. when using `brunch build` post save everything is fine. This issue is likely fine to close.

**Comment by madsflensted** [comment]
thanks for the feedback.
