### ISSUE TITLE
Failing elm-make on 0.11.0 for a config that works on 0.10.0

### ISSUE THREAD

**Issue by savish** [madsflensted/elm-brunch#42]
## Problem
Using the same brunch configuration for an app running phoenix+elm, with one version using elm-brunch 0.10.0 and the other using 0.11.0, the following error always occurs on 0.11.0:

    $ mix phx.server
    ...
    Elm compile: Main.elm, in elm, to ../vendor/main.js
    ...
    elm-make: Main.elm: openFile: does not exist (No such file or directory)

There is no error on the 0.10.0 version. However, the output is slightly different. The `elm-compile` line looks like:

    Elm compile: src/Main.elm, in elm, to ../vendor/main.js

It seems as though the 0.11.0 version cannot locate the `Main.elm` file in the `src` folder. The relevant section of `brunch-config.js` is given below, as well as the elm files, relative to the root (the `assets` folder).

### Possible cause
It seems as though this issue is related to a slight change in the `index.js` file, where the function call to `elmCompile` now receives a `path.basename(src)` as opposed to just the `src`, _even if_ the `independentModules` flag is false.

## Information
- [0.11.0] elm-brunch version
- [2.10.9 ] brunch version
- [9.3.0] nodejs version

brunch-config.js (same for the 0.10.0 and 0.11.0 versions)

    elmBrunch: {
      elmFolder: "elm",
      mainModules: ["src/Main.elm"],
      outputFolder: "../vendor"
    }

File layout:

    assets
      elm
        src
          Main.elm
        elm-package.json
      brunch-config.js

- [macOS - latest] Operating System

**Comment by madsflensted** [comment]
Thank you for reporting this and the detailed information.

@neildaemond can you have a look at this? We will need to expand test to cover this regression.

**Comment by neildaemond** [comment]
Hi, yes thank you for the amount of detail. You are completely right, I can see how this can fail - I just didn't think of elm project with that structure. I'll try rectify that now.

**Comment by neildaemond** [comment]
fixed in https://github.com/madsflensted/elm-brunch/pull/43

**Comment by madsflensted** [comment]
Fix published as 0.11.1
@savish can you give it a try?

**Comment by savish** [comment]
Hey! Works as expected. Thank you for the quick fix!
