### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by Guid75** [madsflensted/elm-brunch#44]
Are you planning an update for Elm 0.19? Or do you accept a patch for this?

**Comment by madsflensted** [comment]
PR will be very welcome.  Probably good idea to think about backwards
compatibility though

**Comment by Voronchuk** [comment]
https://github.com/madsflensted/elm-brunch/pull/45

**Comment by lenards** [comment]
With #45 merged, I think this issue could be closed.

**Comment by madsflensted** [comment]
Yes thanks

**Comment by lenards** [comment]
Thank you, Mads, for your work on elm-brunch.
