### ISSUE TITLE
Can't compile Elm file

### ISSUE THREAD

**Issue by mickeyvip** [madsflensted/elm-brunch#48]
## Problem
![image](https://user-images.githubusercontent.com/220427/55278974-308d3780-5324-11e9-9206-708594b6f568.png)

## Information
- [x] elm-brunch version - `0.12.0`
- [x] brunch version - `2.10.17`
- [x] nodejs version - `10.15.0`
- [x] content of brunch-config.js
```javascript
// See http://brunch.io for documentation.
module.exports = {
  files: {
    javascripts: {
      joinTo: {
        'libraries.js': /^(?!app\/)/,
        'app.js': /^app\//,
      },
    },
    stylesheets: { joinTo: 'app.css' },
  },
  plugins: {
    elmBrunch: {
      mainModules: 'app/elm/Main.elm',
    },
  },
};
```
- [x] content of elm.json (**Elm 0.19**)
```json
{
  "type": "application",
  "source-directories": ["app/elm"],
  "elm-version": "0.19.0",
  "dependencies": {
    "direct": {
      "elm/browser": "1.0.1",
      "elm/core": "1.0.2",
      "elm/html": "1.0.0"
    },
    "indirect": {
      "elm/json": "1.1.3",
      "elm/time": "1.0.0",
      "elm/url": "1.0.0",
      "elm/virtual-dom": "1.0.2"
    }
  },
  "test-dependencies": {
    "direct": {},
    "indirect": {}
  }
}
```
- [x] file layout for your elm files relative to root of project.
![image](https://user-images.githubusercontent.com/220427/55278964-1ce1d100-5324-11e9-9554-83a3b35e74a5.png)

- [x] Operating System - MacOS HighSierra

**Comment by mickeyvip** [comment]
Found 1 of my problems - `mainModules` should be an array.

Now the file compiles:

![image](https://user-images.githubusercontent.com/220427/55292433-ba580600-53f3-11e9-94c5-bcd7b0ddf4fe.png)

But when requiring it - it gets only an empty object:

![image](https://user-images.githubusercontent.com/220427/55292447-d65ba780-53f3-11e9-98b8-b0b026c16684.png)

**Comment by madsflensted** [comment]
Good to hear that you solved the compilation problem. Beware that the elm brunch plugin does not pass the generated code on down the brunch pipeline, as other to-js-transpilers do. So you will need to either include the generated js in your html use other means to get it into the main bundle.

**Comment by mickeyvip** [comment]
@madsflensted , thank you.

Following your advice, I have added `<script src="js/main.js"></script>` to the `index.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Simple Brunch Demo</title>
    <link rel="stylesheet" href="app.css" />
  </head>

  <body>
    <main id="root"></main>
    <h1>
      Brunch
      <small>• A simple demo</small>
    </h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    <script src="libraries.js"></script>
    <script src="js/main.js"></script>
    <script src="app.js"></script>
    <script>
      require('application').init();
    </script>
  </body>
</html>
```
removed the `const Elm = require('./elm/Main.elm');` from the `application.js`.

```javascript
'use strict';
const Greeter = require('./greeter');
const App = {
  init() {
    console.log('App initialized.');
    const g = new Greeter();
    g.greet();
    Elm.Main.init({ node: document.getElementById('root') });
  },
};

module.exports = App;
```

and now it is working:

![image](https://user-images.githubusercontent.com/220427/55342974-b50dc080-54b2-11e9-834a-b62a4dde79ee.png)

**Comment by mickeyvip** [comment]
Maybe it's worth to mention this in the docs? Or did I miss this?
